### ISSUE TITLE
regex_filter_list Issue

### ISSUE THREAD

**Issue by jhaveko** [phantomcyber/playbooks#130]
I think I may have found a bug with the regex_filter_list custom function. I'm running Soar 5.4.0.x.
The action variable for this function is set to be a list. Creating my own version of that CF in SOAR and changing the data type to an item, for the action variable, seems to solve the problem.
Otherwise the community version of that gives this error:

CustomFunctionRun with id=69821 FAILED: The custom function run is being marked failed because all of its constituent results failed
Error: Encountered an unhandled exception in custom function "regex_filter_list" for the parameter dictionary at index=0: {'action': ['drop'], 'input_list': ['10.0.1.1', '10.90.0.1'], 'regex': '\\b(?!10\\.|192\\.168\\.|172\\.(?:1[6-9]|2[0-9]|3[01])\\.)(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(?:\\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}\\b'}
Traceback (most recent call last):
  File "regex_filter_list", line 73, in cfentry
  File "lib3/phantom/decided/playbook_resource_score.py/playbook_resource_score.py", line 126, in _wrapper
  File "lib3/phantom/decided/playbook_resource_score.py/playbook_resource_score.py", line 123, in _wrapper
  File "regex_filter_list", line 25, in regex_filter_list
AttributeError: 'list' object has no attribute 'lower'

**Comment by kelby-shelton** [comment]
Resolved in [08309be8234f8ba8325f7ebefa7eeb1fa02e218c](https://github.com/phantomcyber/playbooks/commit/08309be8234f8ba8325f7ebefa7eeb1fa02e218c)
