### ISSUE TITLE
collect_by_cef_type issue

### ISSUE THREAD

**Issue by TS-MDR** [phantomcyber/playbooks#132]
I see there was a rework on this custom function back in march. I think there is an issue w/ the change. 

At this time :Input is cef types, all, no tags, current container. 

if trying to use the values ouput field, it returns many duplicate values. Manual inspection of the artifacts show that there were only 2 items to be found. But the returned values are those two items repeated many many times.  Havent dug that far in yet, but that's definitely seems like improper behavior. If I get some more time, I'll try to debug as well.

**Comment by TS-MDR** [comment]
cause I can be obsessive, move the definition of cef_dict after next for loop.

`    for cef_key, cef_value in artifact['cef'].items():`
`        cef_dict = {}`

**Comment by kelby-shelton** [comment]
> I see there was a rework on this custom function back in march. I think there is an issue w/ the change.
> 
> At this time :Input is cef types, all, no tags, current container.
> 
> if trying to use the values ouput field, it returns many duplicate values. Manual inspection of the artifacts show that there were only 2 items to be found. But the returned values are those two items repeated many many times. Havent dug that far in yet, but that's definitely seems like improper behavior. If I get some more time, I'll try to debug as well.

@TS-MDR Can you add steps to reproduce?

**Comment by TS-MDR** [comment]
> 

Create a container.
Add 2 artifacts that each have 10 items each. 
mark one cef value as ip, in either artifact.
mark a second cef value as domain in same artifact. 

create a playbook where you call this function, looking for types "ip, domain", all artifacts, current container, no tags. 

run the function and look at the overall output from the function.

when it finds the first instance, it repeats saving it to the output until it finds the 2nd value. Then it repeats saving both values to the output.

**Comment by kelby-shelton** [comment]
@TS-MDR I followed your steps and was not able to reproduce. Are you available on splunk-usergroups slack? If so, can you DM me? I'm Kelby Shelton on there.

**Comment by TS-MDR** [comment]
@kelby-shelton I think i see what's going on. 
Our last sync w community was on march 1st when you first did the update to the function. For whatever reason, it hasn't updated since then. Your comment about in the history about deduplication is exactly what we were seeing. 

I'll kill this issue. Sorry about that!
